:document:
  :source: 'document.glyph'
  :author: ""
  :title: ""
  :subtitle: ""
  :filename: ""
  :draft: false
  :output: 'html'
  :output_targets: [:html, :pdf]
  :bibstyle: 'plain'
:structure:
  :hidden:
    - :imprint
    - :dedication
    - :inspiration
    - :postscript
    - :colophon
    - :promotion
  :special:
    - :foreword
    - :acknowledgement
    - :prologue
    - :epilogue
    - :addendum
    - :glossary
    - :bibliography
    - :references
    - :index
    - :lot
    - :lof
  :frontmatter:
    - :preface
    - :imprint
    - :dedication
    - :inspiration
    - :foreword
    - :introduction
    - :acknowledgement
    - :prologue
  :bodymatter:
    - :volume
    - :book
    - :part
    - :chapter
  :backmatter:
    - :epilogue
    - :afterword
    - :postscript
    - :appendix
    - :addendum
    - :glossary
    - :colophon
    - :bibliography
    - :promotion
    - :references
    - :index
    - :lot
    - :lof
:tools:
  :pdf_generator: 'prince'
:highlighters:
  :target: 'html'
  :current: 'coderay'
  :coderay:
    # See options at http://coderay.rubychan.de/doc/classes/CodeRay/Encoders/HTML.html
    :css: :class 
  :ultraviolet:
    :line_numbers: false
    :theme: 'iplastic'
:filters:
  :by_file_extension: true
  :target: 'html'
  :markdown:
    :converter: 'bluecloth'
  :redcloth:
    :restrictions: []
